### PR TITLE
pytest-arraydiff v0.5.0 

### PR DESCRIPTION
**Pull request by epassaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by epassaro** [comment]
@conda-forge-admin, please rerender

**Comment by epassaro** [comment]
@conda-forge-admin, please rerender

**Comment by epassaro** [comment]
Hi @astrofrog-conda-forge @mwcraig @drdavella,

Is possible to merge this soon to update the package in `conda-forge`?

**Comment by pllim** [comment]
cc @astrofrog and @mwcraig

**Comment by mwcraig** [comment]
> cc @astrofrog and @mwcraig

😱 

@conda-forge-administrative please rerender

**Comment by mwcraig** [comment]
@conda-forge-admin please rerender

**Comment by mwcraig** [comment]
Close/reopen to force re-run of tests

**Comment by pllim** [comment]
Thanks, Matt!

**Comment by mwcraig** [comment]
No problem -- I've turned on notifications for this repo so hopefully it won't take a year next time 😬

**Pull request merged**
